### ISSUE TITLE
lookupAs confusion on my part

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#14]
Hopefully this is another one of my mis-understanderings™ - and as I'm about to leave for a week of glamping it's not urgent.

I'm trying to encode  https://vega.github.io/vega-lite/examples/airport_connections.html which includes the following transforms

```
      "transform": [
        {"filter": {"selection": "single"}},
        {
          "lookup": "origin",
          "from": {
            "data": {"url": "data/airports.csv"},
            "key": "iata",
            "fields": ["latitude", "longitude"]
          }
        },
        {
          "lookup": "destination",
          "from": {
            "data": {"url": "data/airports.csv"},
            "key": "iata",
            "fields": ["latitude", "longitude"]
          },
          "as": ["lat2", "lon2"]
        }
      ],
```

The first one maps to `lookup`, but I can't get the second one to map to `lookupAs`

**Comment by jwoLondon** [comment]
No, not your misunderstanding, just inadequate documentation on my part.

[lookupAs](#https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#lookupAs) allows you to rename the top-level field name. When multiple fields are returned by the lookup, they need to be prefixed with the name you provided using dot notation. So to encode the example above you could do the following:

```elm
trans =
    transform
        << filter (fiSelection "mySelection")
        << lookupAs "origin"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            "o"
        << lookupAs "destination"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            "d"

enc =
    encoding
        << position Longitude [ pName "o.longitude", pMType Quantitative ]
        << position Latitude [ pName "o.latitude", pMType Quantitative ]
        << position Longitude2 [ pName "d.longitude" ]
        << position Latitude2 [ pName "d.latitude" ]
```

It would be possible to make a breaking change to the API allowing a list of aliases as the fourth parameter rather than a single alias as present. I am not sure this would currently be worth it given dot notation can always be used, but happy to hear opinion on this. I also note that Vega-Lite 4 beta introduces a `default` option for failed lookups, which might require a breaking change anyway, so that might be an opportunity to make this change if it is desired.

**Comment by jwoLondon** [comment]
I've restructured `lookup` to accommodate the new (VL4) `default` option and to make naming 'as' more flexible. `lookupAs` is now deprecated. This will be a breaking change in the forthcoming release as it redefines the type signature of `lookup`, but should provide greater flexibility.

The example above is now specified as

```elm
trans =
    transform
        << filter (fiSelection "mySelection")
        << lookup "origin"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            (luAs "o")
        << lookup "destination"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            (luAs "d")
````

You can also replicate the original JSON spec with the following (although I'd argue the spec above is semantically more consistent):

```elm 
trans =
    transform
        << filter (fiSelection "mySelection")
        << lookup "origin"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            (luFields ["latitude", "longitude"])
        << lookup "destination"
            (dataFromUrl "data/airports.csv" [])
            "iata"
            (luFieldsAs [("latitude", "lat2"), ("longitude","lon2")])
````
