### ISSUE TITLE
how to: set Init to multiple values, not a scalar

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#16]
I can't see how to encode

```
  "selection": {
    "brush": {
      "type": "interval",
      "init": {"x": [55, 160], "y": [13, 37]}
    }
  },
```

which is from https://vega.github.io/vega-lite/examples/interactive_brush.html

I don't know if `init` can only sensibly be sent scalar or 2 values, or whether it can support multiple array lengths. This may decide whether a "special case" is needed just for init, or something more complex with `DataValue` (if so then the case at https://github.com/gicentre/elm-vegalite/issues/7#issuecomment-517678789 may also be relevant).

Or I'm sleep deprived and missing something ;-)

**Comment by jwoLondon** [comment]
Thanks. You are right, we cannot currently encode multiple values.

As far as I can tell, the only input selector that can be initialised with more than one value is an interval. And when done so, is always a 2-element number array for `x` and/or a 2 element number array for `y`. This suggests to me that we'd be better off with specific 2-parameter functions for interval initialisation rather than expanding the public API for `dataValue` to include arrays.

**Comment by jwoLondon** [comment]
I've added `seInitInterval` with type signature 

    Maybe ( DataValue, DataValue ) -> Maybe ( DataValue, DataValue )  -> SelectionProperty

to allow x- and y- channel extents to be set individually or in combination. Tuples need to be `DataValue` not `Float` as we can initialise date/time interval selections too.
