### ISSUE TITLE
should rgExtent / dnExtent accept Float rather than DataValue?

### ISSUE THREAD

**Issue by DougBurke** [gicentre/elm-vegalite#25]
From my 'things I thought about while adding to hvega' list. You have

```
dnExtent : DataValue -> DataValue -> DensityProperty
rgExtent : DataValue -> DataValue -> DensityProperty
```

but I think it would be better to have them take `Float` values, since the Vega Lite schema only supports setting these to numbers (unless I'm mis-reading things).

**Comment by jwoLondon** [comment]
I think I gave it a `DataValue` type because the [documentation](https://vega.github.io/vega-lite/docs/density.html#density-transform-definition) (although as you say, not the schema) suggests a range of types are possible. I was anticipating that perhaps temporal data could be validly transformed this way.

Because moving to a `Float` type would be a breaking change, I'll leave this open for now in case the schema is made more flexible in the future. If not, I'll add it for the next major release when we have more substantial changes following breaking changes in Vega-Lite.

**Comment by jwoLondon** [comment]
It would appear that the extent parameters are stably restricted to being floats (as they are in Vega as well as Vega-Lite) so have made the breaking change for the next major release. Thanks for pointing this out.
