### ISSUE TITLE
`loGrouping` should be a list of int

### ISSUE THREAD

**Issue by hingew** [gicentre/elm-vegalite#41]
I just found a little issue that the `loGrouping` function does not work as expected.
According the vega-lite documentation (https://vega.github.io/vega/docs/api/locale/), this needs to be a list of `Int`.

Thank you for you great work :)

**Comment by jwoLondon** [comment]
Thanks for spotting this. I can fix it so that the function signature of `loGrouping` remains with a single integer parameter, but the Vega-Lite specification output is an array (e.g. `[3]`). This would be my preference in terms of leaving this a non-breaking change to the API. 

However, can you anticipate a use-case where we need to provide multiple groupings of different lengths (and so require the ability to supply an array of integers to the function)?

**Comment by hingew** [comment]
Ahh i see. I dont have any use-case for multple groupings. So the signature of the `loGrouping` function can remain as it is. :+1:

**Comment by jwoLondon** [comment]
Added to the next release. I'll close the issue for now, but if anyone has a use case for multiple groupings, I can re-open.
