### ISSUE TITLE
Conversion from elm/time

### ISSUE THREAD

**Issue by RalfNorthman** [gicentre/elm-vegalite#43]
I'm missing some functionality for using elm/time with elm-vegalite. This would be nice to have:

```
posixToDt : Time.Posix -> List DateTime
```

Some context:

Some calculations I'm more comfortable doing in the type safety of Elm, rather than using vega expression strings, but when doing so there can be some friction when trying to put the results of those calculations back into vegalite.

In my own code I now have this:

```
posixToDtList : Time.Posix -> List DateTime
posixToDtList p =
    [ dtYear (Time.toYear Time.utc p)
    , dtMonth (Time.toMonth Time.utc p |> monthConversion)
    , dtDate (Time.toDay Time.utc p)
    , dtHour (Time.toHour Time.utc p)
    , dtMinute (Time.toMinute Time.utc p)
    , dtSecond (Time.toSecond Time.utc p)
    , dtMillisecond (Time.toMillis Time.utc p)
    ]

monthConversion : Time.Month -> MonthName
monthConversion month =
    case month of
        Time.Jan ->
            Jan

        Time.Feb ->
            Feb

        Time.Mar ->
            Mar

        Time.Apr ->
            Apr

        Time.May ->
            May

        Time.Jun ->
            Jun

        Time.Jul ->
            Jul

        Time.Aug ->
            Aug

        Time.Sep ->
            Sep

        Time.Oct ->
            Oct

        Time.Nov ->
            Nov

        Time.Dec ->
            Dec
```

**Comment by jwoLondon** [comment]
Thanks for this. I agree this would be helpful. And given how error prone date-time handling can be, it makes sense to be able to use Elm's Time package, and by implication any other Elm library that can generate Posix times. 

I think it is probably more elm-idiomatic to call the conversion function `fromPosixTime` rather than `to...` so that it more naturally expresses the conversion when used inside an elm-vegalite expression. For example:

```elm
myTime : Time.Posix
myTime = ...

...
enc =
    encoding
        << position X [ pName "dt", pTemporal, pScale [ scDomain <| doMinDt [ fromPosixTime myTime ] ] ]
```

But if you disagree, please feel free to suggest alternatives.

**Comment by RalfNorthman** [comment]
Sounds good!

I think I was inspired by `posixToMillis : Posix -> Int` from elm/time which unwraps `Posix` to the underlying epoch milliseconds.

**Comment by RalfNorthman** [comment]
Since I see you've pushed a commit adding this, I'm closing the issue. Thanks!
