### ISSUE TITLE
The InputProperty type is missing `labels`

### ISSUE THREAD

**Issue by hingew** [gicentre/elm-vegalite#47]
### Description

in the json spec for vega-lite is a `labels` property for select / radio input fields. This can be found in [vega-lite/v5.json](https://vega.github.io/schema/vega-lite/v5.json) under `BindRadioSelect`. 

Thanks for maintaining this package :+1:.

**Comment by jwoLondon** [comment]
Thanks for raising this. I've added three new labelling functions `inLabelledOptions`, `inLabelledDatumOptions` and `inLabelledDataOptions` rather than expose `label` directly. By requiring options to be paired with their corresponding label in a Tuple, this should avoid option->label mismatches. For example,


```elm
ps =
    params
        << param "Style"
            [ paValues (nums [ 0 ])
            , paBind
                (ipSelect
                    [ inLabelledDataOptions
                        [ ( nums [ 0 ], "Solid" )
                        , ( nums [ 2, 2 ], "Dotted" )
                        , ( nums [ 8, 8 ], "Dashed" )
                        ]
                    ]
                )
            ]

mk =
    line [ maNumsExpr "Style" maStrokeDash ]
```

Will appear soon in the next release, but feel free to comment or suggest improvements in the meantime.

**Comment by hingew** [comment]
The changes looks good to me :) Thank you for your fast feedback on this :+1:
